---
- hosts: all
  become: true
  gather_facts: false

  handlers:
    - name: Bounce eth1
      shell: "ifdown eth1; ifup eth1"

  tasks:
    - name: Upgrade all the things
      dnf:
        name: '*'
        state: latest

    - name: Install needed packages
      dnf:
        name:
          - lvm2
          - podman
          - python36
          - vim-enhanced
        state: latest

    - name: Install cephadm
      get_url:
        url: https://raw.githubusercontent.com/ceph/ceph/v16.2.7/src/cephadm/cephadm
        dest: /usr/bin/cephadm
        checksum: sha256:236e76cdb89429f3cf1d47abb5ac6d9d68a93cc10502b7181d02e4b768848c65
        mode: '0755'

    - name: Add my ssh key
      ansible.posix.authorized_key:
        user: vagrant
        key: https://github.com/rubenk.keys

    - name: Enable ipv6
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: 'IPV6INIT="yes"'

    - name: Configure ipv6 ip
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: 'IPV6ADDR="{{ ipv6_ips[inventory_hostname] }}"'
      notify:
        - Bounce eth1

    - name: Allow vagrant user to use ping
      ansible.posix.sysctl:
        name: net.ipv4.ping_group_range
        value: "1000 1000"
      
    - name: setup /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item.value | replace('/64', '') }} {{ item.key }}"
      loop: "{{ ipv6_ips | dict2items }}"
